name: Reusable Workflow

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory in which to run Terraform commands and operations
        type: string
        default: ${{ github.workspace }}
    secrets:
      GH_TOKEN:
        required: true

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  TOKEN: ${{ secrets.PAT_GITHUB1 || '' }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        id: checkout
        with:
          fetch-depth: 0

      - name: Get secret
        run: echo "The secret value is ${TOKEN}"